---
# tasks file for ansible-r-win-domainjoin

- name: Join Domain
  win_domain_membership:
    dns_domain_name: "{{ domainjoin_domain_name }}"
    domain_admin_user: "{{ domainjoin_user_name}}"
    domain_admin_password: "{{ domainjoin_user_pw }}"
    state: domain
  register: domain_state

- name: Reboot (OU) when Domain Member requires it
  win_reboot:
  when: domain_state_ou.changed